namespace Re.Contracts.Products;

public record CreateProductRequest(
    string Code,
    string Name,
    decimal SalePrice,
    decimal VatRate = 20,
    decimal PurchasePrice = 0,
    decimal DealerPrice = 0,
    decimal MinStockLevel = 0,
    decimal MaxStockLevel = 0,
    string? Barcode1 = null,
    string? Barcode2 = null,
    string? Warehouse = null,
    string? SupplierName = null,
    int LeadTimeDays = 0,
    string? Color = null,
    string? Size = null,
    bool IsPublishedEcommerce = false,
    string? SeoTitle = null,
    string? PurchaseAccountCode = null,
    string? SalesAccountCode = null,
    string? ShortName = null,
    string? Description = null,
    Guid? CategoryId = null,
    Guid? BrandId = null,
    Guid? UnitId = null,
    bool TrackStock = true,
    string? ImagePath = null,
    IReadOnlyCollection<SaveProductVariantRequest>? Variants = null);

public record UpdateProductRequest(
    string Name,
    decimal SalePrice,
    decimal VatRate,
    decimal PurchasePrice,
    decimal DealerPrice,
    decimal MinStockLevel,
    decimal MaxStockLevel,
    string? Barcode1,
    string? Barcode2,
    string? Warehouse,
    string? SupplierName,
    int LeadTimeDays,
    string? Color,
    string? Size,
    bool IsPublishedEcommerce,
    string? SeoTitle,
    string? PurchaseAccountCode,
    string? SalesAccountCode,
    string? ShortName,
    string? Description,
    Guid? CategoryId,
    Guid? BrandId,
    Guid? UnitId,
    bool IsActive,
    string? ImagePath = null);

public record ProductResponse(
    Guid Id,
    string Code,
    string Name,
    string? ShortName,
    decimal SalePrice,
    decimal PurchasePrice,
    decimal DealerPrice,
    decimal VatRate,
    decimal MinStockLevel,
    decimal MaxStockLevel,
    string? Barcode1,
    string? Barcode2,
    string? Warehouse,
    string? SupplierName,
    int LeadTimeDays,
    string? Color,
    string? Size,
    bool IsPublishedEcommerce,
    string? SeoTitle,
    string? PurchaseAccountCode,
    string? SalesAccountCode,
    string? CategoryName,
    string? BrandName,
    string? UnitName,
    bool IsActive,
    DateTime CreatedAt,
    string? ImagePath = null);

public record ProductListResponse(
    Guid Id,
    string Code,
    string Name,
    decimal PurchasePrice,
    decimal SalePrice,
    decimal DealerPrice,
    decimal VatRate,
    decimal MinStockLevel,
    decimal MaxStockLevel,
    string? Barcode,
    string? CategoryName,
    Guid? CategoryId,
    string? BrandName,
    Guid? BrandId,
    string? Warehouse,
    decimal StockLevel,
    string? ImagePath,
    DateTime LastUpdatedAt,
    bool IsActive);

public record AddBarcodeRequest(string Value, string BarcodeType = "EAN13");
public record SaveProductVariantRequest(
    string Code, string? Color, string? Size, string? Attribute1, string? Attribute2,
    decimal SalePrice, bool IsActive = true);
public record ProductVariantResponse(
    Guid Id, Guid ProductId, string Code, string? Color, string? Size,
    string? Attribute1, string? Attribute2, decimal SalePrice, bool IsActive);

